// --- Attributes ---
export const ATTR = { ELEMENT: 0, POTENCY: 1, STATE: 2, ORIGIN: 3 };

export const ELEMENT_NAMES  = ['foc', 'aigua', 'terra', 'aire'];
export const POTENCY_VALUES = [1, 2, 3];
export const STATE_NAMES    = ['sòlid', 'líquid', 'gas'];
export const ORIGIN_NAMES   = ['natural', 'arcà', 'buit'];

// Number of possible values per attribute slot (scales with difficulty)
export const DEFAULT_VALUES_PER_ATTR = 3;

// --- Combo rules ---
export const MIN_COMBO = 3;
export const MAX_COMBO = 5;

// --- Scoring ---
// Base score by combo size (indices 0-2 unused)
export const SCORE_BY_SIZE = [0, 0, 0, 100, 250, 600];
export const SCORE_TYPE_MULT = { pure: 2.0, chaos: 1.5, mixed: 1.0 };
export const SCORE_CASCADE_BASE = 1.5; // per cascade level

// --- Board defaults ---
export const DEFAULT_COLS = 5;
export const DEFAULT_ROWS = 8;

// --- Solvability enforcement ---
export const MAX_INJECT_ATTEMPTS = 10;

// --- Catalitzador (philosopher's stone) ---
// Generated by a size-5 combo; clears a full row
export const CATALYST_SIZE = 5;
