import { DEFAULT_VALUES_PER_ATTR } from './constants.js';

export class Piece {
  /**
   * @param {number[]} attrs - [elementIdx, potencyIdx, stateIdx, originIdx]
   * @param {boolean} special - philosopher's catalyst (generated by size-5 combo)
   */
  constructor(attrs, special = false) {
    this.attrs = attrs;
    this.special = special;
  }

  static random(valuesPerAttr = DEFAULT_VALUES_PER_ATTR) {
    return new Piece([
      Math.floor(Math.random() * valuesPerAttr),
      Math.floor(Math.random() * valuesPerAttr),
      Math.floor(Math.random() * valuesPerAttr),
      Math.floor(Math.random() * valuesPerAttr),
    ]);
  }

  clone() {
    return new Piece([...this.attrs], this.special);
  }
}
