'use strict';

const GAME_DATA = {

  // ── Global data (shared across all eras) ─────────────────────────────────

  resources: [
    { id: 'food',             name: 'Menjar',             icon: '🍖', initial: 40, max: 100, visibleAfterTech: null,                  hasForecast: true  },
    { id: 'health',           name: 'Salut',              icon: '❤️', initial: 80, max: 100, visibleAfterTech: null,                  hasForecast: true  },
    { id: 'happiness',        name: 'Felicitat',          icon: '😊', initial: 60, max: 100, visibleAfterTech: 'language_basics',     hasForecast: true  },
    { id: 'familyReputation', name: 'Reputació Familiar', icon: '🏛️', initial: 0,  max: 100, visibleAfterTech: 'tribal_organization', hasForecast: false },
  ],

  charStats: [
    { id: 'physical',     icon: '💪', visibleAfterTech: null },
    { id: 'intelligence', icon: '🧠', visibleAfterTech: null },
    { id: 'social',       icon: '👥', visibleAfterTech: 'language_basics' },
  ],

  traits: [
    { id: 'great_strength',     name: 'Força excepcional',  icon: '⚡', statKey: 'physical',
      desc: 'Salut màxima incrementada en 15.',
      effect: { maxHealth: 15 }, inheritChance: 0.4 },
    { id: 'natural_resilience', name: 'Resistència natural', icon: '🛡️', statKey: 'physical',
      desc: 'L\'envelliment li afecta la meitat.',
      effect: { agingResistFactor: 0.5 }, inheritChance: 0.5 },
    { id: 'sharp_intuition',    name: 'Intuïció afilada',   icon: '🔮', statKey: 'intelligence',
      desc: 'Descobreix coneixements amb +20% de probabilitat.',
      effect: { discoveryBonus: 0.2 }, inheritChance: 0.3 },
    { id: 'quick_learner',      name: 'Aprenent ràpid',     icon: '📖', statKey: 'intelligence',
      desc: 'Guanya habilitats un 25% més ràpidament.',
      effect: { statGainBonus: 0.25 }, inheritChance: 0.3 },
    { id: 'born_leader',        name: 'Líder nat',           icon: '👑', statKey: 'social',
      desc: 'Comença amb +10 reputació familiar.',
      effect: { stat: 'familyReputation', value: 10 }, inheritChance: 0.35 },
    { id: 'gift_of_speech',     name: 'Do de la paraula',   icon: '🗣️', statKey: 'social',
      desc: 'Carisma innat: +1 Social.',
      effect: { stat: 'social', value: 1 }, inheritChance: 0.4 },
    { id: 'adaptable',          name: 'Adaptable',           icon: '🌿', statKey: 'balanced',
      desc: 'S\'adapta a qualsevol situació: +15 Felicitat inicial.',
      effect: { stat: 'happiness', value: 15 }, inheritChance: 0.25 },
  ],

  dynastyTitles: [
    { minMilestones: 5,  label: 'Llegenda Viva' },
    { requires: ['dynasty_founded', 'tribe_respected'], label: "Constructors d'Imperis" },
    { requires: ['all_knowledge'],   label: 'La Línia dels Savis' },
    { requires: ['great_hunter'],    label: 'Guerrers de la Prehistòria' },
    { requires: ['family_complete'], label: 'La Família Completa' },
    { default: true, label: 'Fills de la Terra' },
  ],

  namesMasc: ['Brac', 'Arn', 'Dal', 'Kur', 'Mog', 'Thag', 'Bok', 'Drak', 'Fal', 'Gar', 'Huk', 'Jok'],
  namesFem:  ['Mira', 'Sela', 'Una', 'Bera', 'Kala', 'Thea', 'Nara', 'Lira', 'Vela', 'Hara', 'Yuna', 'Asha'],

  virtueLabels: {
    physical:     ['La seva força és llegendària des de petit', 'El cos mai li falla quan importa', 'Nascut/da per a la cacera'],
    intelligence: ['Té un talent innat per entendre el món', 'La curiositat el/la guia on altres no s\'atreveixen', 'La ment sempre un pas endavant'],
    social:       ['Fa amics allà on va', 'La tribu el/la segueix sense dubtar', 'Té el do de la paraula'],
    balanced:     ['No destaca en res però mai falla en res', 'Un equilibri que pocs assoleixen', 'La fiabilitat és la seva virtut'],
  },

  milestones: [
    { id: 'first_fire',      name: 'Mestre del Foc',        icon: '🔥', desc: 'Descobrir el foc',               points: 300 },
    { id: 'great_hunter',    name: 'Gran Caçador/a',         icon: '🦣', desc: '5 caceres exitoses',             points: 250, check: { type: 'char', key: 'huntCount', value: 5 } },
    { id: 'long_lived',      name: 'Longeu/a',               icon: '⏳', desc: 'Sobreviure fins als 40+ anys',   points: 200, check: { type: 'char', key: 'age', value: 40 } },
    { id: 'dynasty_founded', name: 'Fundador/a de Dinastia', icon: '🏛️', desc: 'Iniciar la 2a generació',        points: 400 },
    { id: 'all_knowledge',   name: 'Buscador/a de Saviesa',  icon: '📜', desc: 'Descobrir totes les tecnologies', points: 350 },
    { id: 'tribe_respected', name: 'Respectat/da per la Tribu', icon: '👑', desc: 'Reputació > 50',             points: 300, check: { type: 'resource', key: 'familyReputation', value: 50 } },
    { id: 'family_complete', name: 'Família Completa',       icon: '👨‍👩‍👧', desc: 'Tenir parella i 2+ fills',       points: 300, check: { type: 'family', value: 2 } },
    { id: 'era_transition',  name: 'Nova Era',               icon: '🌅', desc: 'Arribar al Neolític',            points: 500 },
  ],

  // ── Eras — all game content nested per era ────────────────────────────────
  eras: [

    // ══════════════════════════════════════════════════════════════════════
    //  ERA 1 — PREHISTÒRIA
    // ══════════════════════════════════════════════════════════════════════
    {
      id: 'prehistoria',
      name: 'Prehistòria',
      icon: '🦴',
      lifeExpectancy: { base: 30, max: 45 },
      cyclesPerLife: { base: 12, max: 15 },
      agingCurve: {
        threshold: 7,
        baseLoss: 5,
        acceleration: 1.7,
      },
      maxChildren: 6,
      startingStats: { physical: 1, intelligence: 1, social: 1 },
      timeTotal: 6,
      foodPerTimePoint: 1.7,
      duration: 60,
      globalEvents: ['harsh_winter', 'tribe_conflict'],
      dynastySuffixes: ['de la Roca', 'del Foc', 'de la Tribu', 'del Vent', 'de les Cavernes'],
      mechanics: {
        intensityOutputMults: [0.5, 1.1, 1.8],
        intensityRiskMults:   [0.4, 1.0, 2.2],
        intensityFailChances: [0.15, 0.3, 0.55],
        intensityTimeCosts:   [2, 4, 6],
        intensityLabels:      ['🌱 Suau', '⚡ Normal', '🔥 Intens'],
        statModBase:    0.65,
        statModPerStat: 0.12,
        statModMin:     0.5,
        statModMax:     1.8,
        knowledgeBonusPerTech: 0.15,
        maxLearnedSkills: 2,
        skillDiscoveryMinScore: 0.3,
        happinessDrift:   -3,
        happinessMin:     20,
        familyRepBonus:   2,
        childrenFoodCost: 2,
        famineModerate:        0.3,
        famineSevere:          0.6,
        famineChildDeathRisk:  0.8,
        famineHealthMult:      1.5,
        famineMaxLossModerate: 2,
        famineMaxLossSevere:   5,
        healthMaxFloor:        30,
        grownChildCycles:    3,
        grownChildBonus:     2,
        grownChildMaxCount:  2,
        largeChildThreshold: 3,
        largeChildBonus:     2,
        teachCostBase:      2,
        teachCostIncrement: 1,
        eventTriggerChance:  0.28,
        globalEventMinCycle: 4,
        globalEventChance:   0.1,
        partnerStatDivisor:       1.5,
        successionPhysicalFactor: 0.3,
        scorePerGeneration: 400,
        scorePerRep:        5,
        scorePerKnowledge:  100,
      },

      zones: [
        {
          id: 'wild', name: 'Camp', icon: '🌿',
          description: 'Recol·lecta i observa la natura',
          discoveryTitle: 'El camp us alimenta',
          discoveryText: 'La tribu aprèn a llegir la terra. Cada arrel, cada baia, cada rastre és una lliçó de supervivència que es transmet de generació en generació.',
        },
        {
          id: 'town', name: 'Poblat', icon: '🏛️',
          description: 'Socialitza i fabrica eines',
          discoveryTitle: 'Neix el poblat',
          discoveryText: 'El lloc on la tribu es troba, fabrica i discuteix. Aquí les mans transformen la pedra en eines i les idees en costums.',
        },
        {
          id: 'forest', name: 'Bosc', icon: '🌲',
          description: 'Caça i explora terres llunyanes',
          discoveryTitle: 'El bosc reclama el seu preu',
          discoveryText: 'Ets prou fort per endinsar-te on les preses s\'amaguen. Aquí la vida és abundant i perillosa a parts iguals. Qui domina el bosc, domina la supervivència.',
        },
        {
          id: 'home', name: 'Llar', icon: '🏠',
          description: 'Descansa i cuida la família',
          discoveryTitle: 'Un lloc al món',
          discoveryText: 'Per primer cop, la tribu crea un lloc que no és simplement refugi. És llar. I una llar implica família, rols i futures generacions.',
        },
      ],

      // Technologies — worldwide, auto-unlock at eraCycleAppears
      techs: [
        {
          id: 'language_basics', name: 'Llengua Bàsica', icon: '🗣️',
          eraCycleAppears: 2,
          description: 'Comunicar-se millor enforteix els llaços tribals. La tribu comença a organitzar-se.',
          statBonus: { social: 1 }, inheritanceRate: 1.0,
          unlocksActionIds: [],
        },
        {
          id: 'tribal_organization', name: 'Organització Tribal', icon: '👥',
          eraCycleAppears: 8,
          description: 'Rols i normes emergents. La tribu funciona com una unitat.',
          statBonus: {}, inheritanceRate: 1.0,
          unlocksActionIds: ['find_partner', 'care_home'],
        },
        {
          id: 'fire', name: 'Domini del Foc', icon: '🔥',
          eraCycleAppears: 18,
          description: 'Dominar el foc canvia les possibilitats de la tribu. Calor, cuina i protecció.',
          effectDesc: '+5 Salut màxima permanent.',
          statBonus: { health: 5 }, inheritanceRate: 1.0,
          unlocksActionIds: ['cook_food'],
        },
        {
          id: 'stone_tools', name: 'Eines de Pedra', icon: '🪨',
          eraCycleAppears: 28,
          description: 'Eines millorades per a la caça i l\'exploració. Redueix el risc de caça.',
          statBonus: {}, inheritanceRate: 1.0,
          unlocksActionIds: ['explore'],
        },
        {
          id: 'symbolic_thinking', name: 'Pensament Simbòlic', icon: '🧿',
          eraCycleAppears: 38,
          description: 'Conceptes abstractes, art i espiritualitat. Nous horitzons de la ment.',
          statBonus: { intelligence: 1 }, inheritanceRate: 1.0,
          unlocksActionIds: [],
        },
        {
          id: 'sedentarism', name: 'Sedentarisme', icon: '🏕️',
          eraCycleAppears: 47,
          description: 'La tribu s\'estableix en un lloc fix. Noves pràctiques familiars i d\'emmagatzematge.',
          statBonus: {}, inheritanceRate: 1.0,
          unlocksActionIds: [],
        },
        // Gate-tech: triggers transition to Neolític
        {
          id: 'agricultura', name: 'Agricultura', icon: '🌾',
          eraCycleAppears: 55,
          isGateTech: true, nextEra: 'neolitic',
          description: 'La tribu descobreix com cultivar la terra de manera intencionada. Una nova era comença.',
          effectDesc: 'Inicia la transició cap al Neolític.',
          statBonus: { intelligence: 1 }, inheritanceRate: 1.0,
          unlocksActionIds: [],
        },
      ],

      // Skills (habilitats) — 2 per tech, lineage-level, optional
      skills: [
        { id: 'persuasion', name: 'Persuasió', icon: '🗣️',
          description: 'El llinatge desenvolupa l\'art de convèncer i negociar amb altres grups.',
          requiresTech: 'language_basics', requiresMinStat: { social: 2 },
          unlocksActionIds: ['negotiate', 'mediate_conflict'],
          effectDesc: 'Desbloqueja Negociar i Mediar Conflictes' },
        { id: 'oral_tradition', name: 'Tradició Oral', icon: '📖',
          description: 'El llinatge preserva el coneixement ancestral a través de contes i cants.',
          requiresTech: 'language_basics', requiresMinStat: { intelligence: 2 },
          unlocksActionIds: ['tell_stories', 'teach_group'],
          effectDesc: 'Desbloqueja Contar Gestes i Ensenyar en Grup' },
        { id: 'chieftainship', name: 'Lideratge Tribal', icon: '👑',
          description: 'El llinatge pren el paper de líders naturals dins la tribu.',
          requiresTech: 'tribal_organization', requiresMinStat: { social: 3 },
          unlocksActionIds: ['rally_tribe', 'lead_hunt'],
          effectDesc: 'Desbloqueja Mobilitzar la Tribu i Caça Organitzada' },
        { id: 'barter_trade', name: 'Bescanvi', icon: '🤝',
          description: 'El llinatge estableix xarxes d\'intercanvi amb tribus veïnes.',
          requiresTech: 'tribal_organization', requiresMinStat: { intelligence: 2 },
          unlocksActionIds: ['trade_resources', 'establish_trade_route'],
          effectDesc: 'Desbloqueja Bescanviar Recursos i Ruta Comercial' },
        { id: 'cooking_mastery', name: 'Art Culinari', icon: '🍳',
          description: 'El llinatge domina les tècniques culinàries avançades: festins i conservació.',
          requiresTech: 'fire', requiresMinStat: { intelligence: 2 },
          unlocksActionIds: ['cook_feast', 'preserve_food'],
          effectDesc: 'Desbloqueja Gran Festí i Conservar Aliments' },
        { id: 'fire_techniques', name: 'Tècniques del Foc', icon: '🔥',
          description: 'El llinatge usa el foc com a eina de caça nocturna i comunicació a distància.',
          requiresTech: 'fire', requiresMinStat: { physical: 2 },
          unlocksActionIds: ['torch_hunt', 'signal_fires'],
          effectDesc: 'Desbloqueja Caça amb Torxes i Senyals de Foc' },
        { id: 'big_game_hunting', name: 'Caça Major', icon: '🦣',
          description: 'El llinatge domina la caça de les grans preses de la prehistòria.',
          requiresTech: 'stone_tools', requiresMinStat: { physical: 3 },
          unlocksActionIds: ['hunt_mammoth', 'hunt_bison'],
          effectDesc: 'Desbloqueja Caçar el Mamut i Caçar el Bisó' },
        { id: 'advanced_crafting', name: 'Artesania Avançada', icon: '🪨',
          description: 'El llinatge perfecciona l\'elaboració d\'armes i ornaments de pedra i os.',
          requiresTech: 'stone_tools', requiresMinStat: { intelligence: 3 },
          unlocksActionIds: ['craft_weapons', 'craft_ornaments'],
          effectDesc: 'Desbloqueja Forjar Armes i Crear Ornaments' },
        { id: 'shamanism', name: 'Xamanisme', icon: '🧿',
          description: 'El llinatge connecta amb el món espiritual i guia la tribu en rituals sagrats.',
          requiresTech: 'symbolic_thinking', requiresMinStat: { social: 2 },
          unlocksActionIds: ['healing_ritual', 'spirit_ceremony'],
          effectDesc: 'Desbloqueja Ritual Curatiu i Cerimònia Espiritual' },
        { id: 'cave_art', name: 'Art Rupestre', icon: '🎨',
          description: 'El llinatge immortalitza les seves gestes i visions a les parets de les coves.',
          requiresTech: 'symbolic_thinking', requiresMinStat: { intelligence: 2 },
          unlocksActionIds: ['paint_cave', 'carve_symbols'],
          effectDesc: 'Desbloqueja Pintura Rupestre i Gravar Símbols' },
        { id: 'proto_agriculture', name: 'Proto-Agricultura', icon: '🌾',
          description: 'El llinatge comença a cultivar plantes de manera intencionada.',
          requiresTech: 'sedentarism', requiresMinStat: { intelligence: 2 },
          unlocksActionIds: ['plant_seeds', 'tend_crops'],
          effectDesc: 'Desbloqueja Plantar Llavors i Conrear' },
        { id: 'shelter_building', name: 'Construcció de Refugis', icon: '🏗️',
          description: 'El llinatge construeix estructures permanents per protegir la tribu.',
          requiresTech: 'sedentarism', requiresMinStat: { physical: 2 },
          unlocksActionIds: ['build_shelter', 'fortify_camp'],
          effectDesc: 'Desbloqueja Construir Refugi i Fortificar el Camp' },
      ],

      // Actions — 10 base + 24 habilitat-gated
      actions: [
        // ── Base actions ──
        { id: 'gather', name: 'Recol·lectar', icon: '🌿', category: 'survival',
          description: 'Baies, arrels i bolets. Segur però lent.',
          requirements: {}, requiresTech: null, statKey: 'intelligence',
          outputs: { food: 15, happiness: 5, health: 2 }, healthRisk: 0,
          knowledgeBonus: ['stone_tools'], techBonuses: { stone_tools: { foodPct: 0.3 } },
          statGain: { intelligence: 0.3 }, destreseDiscovery: ['medicinal_plants', 'fishing'],
          eventPool: ['good_harvest', 'found_herb'], zone: 'wild',
          successTexts: ['Collita generosa!', 'El camp ens alimenta.', 'Prou per uns dies.'],
          failTexts: ['Poca cosa avui.', 'El bosc no dóna molt.'] },
        { id: 'observe_nature', name: 'Observar la Natura', icon: '🔍', category: 'knowledge',
          description: 'Contemplar l\'entorn. Acumula coneixement i pau interior.',
          requirements: {}, requiresTech: null, statKey: 'intelligence',
          outputs: { happiness: 18 }, healthRisk: 0, knowledgeBonus: [],
          statGain: { intelligence: 0.6 }, destreseDiscovery: ['medicinal_plants', 'art_narratiu'],
          eventPool: [], zone: 'wild',
          successTexts: ['El món s\'obre als teus ulls.', 'Nova comprensió de la natura.', 'Descobreixes patrons ocults.'],
          failTexts: ['La ment vaga avui.', 'Reflexió sense conclusions.'] },
        { id: 'hunt', name: 'Caçar', icon: '🏹', category: 'survival',
          description: 'Sortir a caçar. Risc moderat, bona recompensa.',
          requirements: { physical: 2 }, requiresTech: null, statKey: 'physical',
          outputs: { food: 22 }, healthRisk: 10, riskReductions: { stone_tools: 0.5 },
          knowledgeBonus: ['stone_tools'], statGain: { physical: 0.4 },
          destreseDiscovery: ['tracking'], eventPool: ['rival_hunter', 'injured_companion', 'great_prey'],
          zone: 'forest',
          successTexts: ['Bona caça! La tribu celebra.', 'Gran presa avui!', 'El bosc ens ha alimentat.'],
          failTexts: ['Caça escassa.', 'Les preses ens escapen.', 'Tornem amb poc.'] },
        { id: 'craft_tools', name: 'Fabricar Eines', icon: '🪨', category: 'knowledge',
          description: 'Treballa la pedra i l\'os. Enforteix la ment i les mans.',
          requirements: {}, requiresTech: null, statKey: 'intelligence',
          outputs: { happiness: 8, familyReputation: 3 }, healthRisk: 0, knowledgeBonus: [],
          statGain: { intelligence: 0.5, physical: 0.15 }, destreseDiscovery: ['weaving'],
          eventPool: [], zone: 'town',
          successTexts: ['Noves tècniques descobertes!', 'Les eines milloren.', 'La pedra revela els seus secrets.'],
          failTexts: ['Poc progrés avui.', 'Necessites més pràctica.'] },
        { id: 'find_partner', name: 'Buscar Parella', icon: '💑', category: 'home',
          description: 'Socialitzar per trobar algú amb qui compartir el camí.',
          requirements: { social: 2 }, requiresTech: 'tribal_organization', requiresNoPartner: true,
          statKey: 'social', outputs: { happiness: 20, familyReputation: 5 }, healthRisk: 0,
          knowledgeBonus: [], statGain: { social: 0.5 }, destreseDiscovery: ['socialitzar'],
          generatesPartner: true, eventPool: ['rival_suitor'], zone: 'town',
          successTexts: ['Has trobat algú especial.', 'La tribu celebra la unió.', 'Un nou capítol comença.'],
          failTexts: ['No és el moment.', 'El cor és pacient.'] },
        { id: 'have_children', name: 'Tenir Fills', icon: '👶', category: 'home',
          description: 'Créixer com a família. Genera 1 fill si la qualitat és suficient.',
          requirements: { health: 40, requiresPartner: true }, requiresTech: null,
          statKey: 'social', outputs: { happiness: 15 }, healthRisk: 0, knowledgeBonus: [],
          statGain: { social: 0.3 }, destreseDiscovery: [], generatesChild: true,
          eventPool: [], zone: 'home',
          successTexts: ['Benvingut/da al món!', 'El llinatge creix.', 'Un nou cor batega.'],
          failTexts: ['No és el moment per ampliar la família.'] },
        { id: 'care_home', name: 'Cuidar la Llar', icon: '🏠', category: 'home',
          description: 'Descansa i enforteix els llaços de la tribu. Recupera salut.',
          requirements: {}, requiresTech: 'tribal_organization', statKey: 'social',
          outputs: { health: 15, happiness: 12, familyReputation: 3 }, healthRisk: 0,
          knowledgeBonus: [], statGain: { social: 0.3 },
          destreseDiscovery: ['weaving', 'socialitzar', 'cooking'],
          eventPool: ['tribe_conflict', 'epidemic'], zone: 'home',
          successTexts: ['La tribu et recorda.', 'El descans et revitalitza.', 'La llar és font de força.'],
          failTexts: ['Difícil trobar calma avui.'] },
        { id: 'cook_food', name: 'Cuinar', icon: '🍳', category: 'home',
          description: 'Cuina els aliments sobre el foc. Recupera forces i millora l\'ànim.',
          requirements: {}, requiresTech: 'fire', statKey: 'intelligence',
          outputs: { health: 12, happiness: 15 }, healthRisk: 0, knowledgeBonus: ['fire'],
          statGain: { intelligence: 0.2 }, destreseDiscovery: ['cooking'],
          eventPool: [], zone: 'home',
          successTexts: ['L\'olor del foc omple la cova.', 'El menjar calent reconforta la tribu.', 'Un àpat senzill però nutritiu.'],
          failTexts: ['El foc no vol cremar avui.', 'El resultat és mediocre.'] },
        { id: 'educate_child', name: 'Educar Fills', icon: '📖', category: 'home',
          description: 'Transmet una de les teves habilitats a un fill.',
          requirements: { requiresChild: true, requiresLearnedSkill: true }, requiresTech: null,
          statKey: 'social', outputs: { happiness: 8, familyReputation: 3 }, healthRisk: 0,
          knowledgeBonus: [], statGain: { social: 0.2, intelligence: 0.1 },
          destreseDiscovery: [], teachesSkill: true, eventPool: [], zone: 'home',
          successTexts: ['El fill aprèn ràpidament.', 'Un moment inoblidable.', 'Sents com el llinatge creix en saviesa.'],
          failTexts: [] },
        { id: 'explore', name: 'Explorar', icon: '🗺️', category: 'survival',
          description: 'Aventurar-se lluny. Risc alt, recursos rars.',
          requirements: { physical: 3 }, requiresTech: 'stone_tools', statKey: 'physical',
          outputs: { food: 8 }, healthRisk: 16, knowledgeBonus: ['stone_tools'],
          statGain: { physical: 0.5, intelligence: 0.2 },
          destreseDiscovery: ['tracking', 'fishing'],
          eventPool: ['found_shelter', 'injured_companion', 'neighboring_tribe'], zone: 'forest',
          successTexts: ['Terres noves! Recursos inesperats.', 'L\'horitzó et recompensa.', 'Una troballa excepcional.'],
          failTexts: ['El camí és dur i perillós.', 'Tornes cansat i buit.'] },
        // ── Persuasion ──
        { id: 'negotiate', name: 'Negociar', icon: '🤲', category: 'home',
          description: 'Estableix acords beneficiosos amb tribus veïnes.',
          requirements: {}, requiresSkill: 'persuasion', statKey: 'social',
          outputs: { food: 12, happiness: 15, familyReputation: 10 }, healthRisk: 0,
          knowledgeBonus: ['tribal_organization'], statGain: { social: 0.5 },
          destreseDiscovery: ['socialitzar'], eventPool: ['neighboring_tribe'], zone: 'town',
          successTexts: ['L\'acord és just per a tothom.', 'Les paraules eviten el conflicte.'],
          failTexts: ['Les negociacions fracassen.', 'No hi ha entesa possible ara.'] },
        { id: 'mediate_conflict', name: 'Mediar Conflicte', icon: '⚖️', category: 'home',
          description: 'Resol disputes internes i enforteix la cohesió tribal.',
          requirements: {}, requiresSkill: 'persuasion', statKey: 'social',
          outputs: { familyReputation: 15, happiness: 10 }, healthRisk: 0, knowledgeBonus: [],
          statGain: { social: 0.4 }, destreseDiscovery: ['socialitzar'], eventPool: [], zone: 'town',
          successTexts: ['La pau torna a la tribu.', 'El teu lideratge és reconegut.'],
          failTexts: ['El conflicte s\'agreuja.', 'Cap costat cedeix avui.'] },
        // ── Oral Tradition ──
        { id: 'tell_stories', name: 'Contar Gestes', icon: '🔥', category: 'knowledge',
          description: 'Narra les gestes ancestrals al voltant del foc. La tribu recorda i s\'enforteix.',
          requirements: {}, requiresSkill: 'oral_tradition', statKey: 'intelligence',
          outputs: { happiness: 20, familyReputation: 5 }, healthRisk: 0,
          knowledgeBonus: ['symbolic_thinking'], statGain: { intelligence: 0.4 },
          destreseDiscovery: ['art_narratiu'], eventPool: ['spiritual_vision'], zone: 'home',
          successTexts: ['La tribu escolta embadalida.', 'Les gestes ancestrals viuen de nou.'],
          failTexts: ['Les paraules no troben el ritme avui.', 'La tribu s\'adorm aviat.'] },
        { id: 'teach_group', name: 'Ensenyar en Grup', icon: '🧑‍🏫', category: 'knowledge',
          description: 'Transmissió estructurada de coneixement a tota la tribu alhora.',
          requirements: {}, requiresSkill: 'oral_tradition', statKey: 'intelligence',
          outputs: { familyReputation: 10, happiness: 8 }, healthRisk: 0, knowledgeBonus: [],
          statGain: { intelligence: 0.5, social: 0.1 },
          destreseDiscovery: ['art_narratiu', 'weaving'], eventPool: [], zone: 'home',
          successTexts: ['El coneixement es difon per tota la tribu.', 'La tribu aprèn junta.'],
          failTexts: ['La sessió és desorganitzada.', 'La tribu no posa atenció avui.'] },
        // ── Chieftainship ──
        { id: 'rally_tribe', name: 'Mobilitzar la Tribu', icon: '📯', category: 'home',
          description: 'Convoca la tribu i organitza esforços col·lectius.',
          requirements: {}, requiresSkill: 'chieftainship', statKey: 'social',
          outputs: { familyReputation: 25, happiness: 15 }, healthRisk: 0,
          knowledgeBonus: ['tribal_organization'], statGain: { social: 0.5 },
          destreseDiscovery: ['socialitzar'], eventPool: [], zone: 'town',
          successTexts: ['La tribu respon al teu crit.', 'El teu lideratge uneix els cors.'],
          failTexts: ['La tribu no et segueix avui.', 'Les disputes internes debiliten la unitat.'] },
        { id: 'lead_hunt', name: 'Caça Organitzada', icon: '🦬', category: 'survival',
          description: 'Lidera una caça col·lectiva. Menjar abundant per a tota la tribu.',
          requirements: { physical: 2 }, requiresSkill: 'chieftainship', statKey: 'physical',
          outputs: { food: 35, familyReputation: 10 }, healthRisk: 8,
          riskReductions: { stone_tools: 0.4 }, knowledgeBonus: ['stone_tools'],
          statGain: { physical: 0.4, social: 0.3 }, destreseDiscovery: ['tracking'],
          eventPool: ['great_prey', 'dangerous_prey'], zone: 'forest',
          successTexts: ['La caça col·lectiva és un triomf.', 'El teu lideratge porta menjar abundant.'],
          failTexts: ['La caça s\'escapa.', 'La coordinació falla avui.'] },
        // ── Barter Trade ──
        { id: 'trade_resources', name: 'Bescanviar Recursos', icon: '🔄', category: 'home',
          description: 'Intercanvia excedents amb tribus veïnes per recursos que necessites.',
          requirements: {}, requiresSkill: 'barter_trade', statKey: 'social',
          outputs: { food: 15, happiness: 10, familyReputation: 8 }, healthRisk: 0,
          knowledgeBonus: ['tribal_organization'], statGain: { social: 0.3, intelligence: 0.2 },
          destreseDiscovery: ['socialitzar'], eventPool: ['neighboring_tribe'], zone: 'town',
          successTexts: ['L\'intercanvi és fructífer.', 'Noves relacions comercials establertes.'],
          failTexts: ['El bescanvi no surt bé.', 'L\'altra tribu no confia prou.'] },
        { id: 'establish_trade_route', name: 'Ruta Comercial', icon: '🛤️', category: 'home',
          description: 'Estableix una ruta permanent d\'intercanvi. El llinatge es fa conegut.',
          requirements: {}, requiresSkill: 'barter_trade', statKey: 'intelligence',
          outputs: { familyReputation: 22, happiness: 8 }, healthRisk: 0, knowledgeBonus: [],
          statGain: { intelligence: 0.4, social: 0.2 }, destreseDiscovery: [], eventPool: [], zone: 'town',
          successTexts: ['Una ruta permanent s\'estableix.', 'El llinatge es fa conegut per la seva xarxa.'],
          failTexts: ['La ruta és massa perillosa ara.', 'Cap tribu vol comprometre\'s.'] },
        // ── Cooking Mastery ──
        { id: 'cook_feast', name: 'Gran Festí', icon: '🍖', category: 'home',
          description: 'Prepara un festí per a tota la tribu. Cohesió i alegria màximes.',
          requirements: {}, requiresSkill: 'cooking_mastery', statKey: 'intelligence',
          outputs: { happiness: 30, familyReputation: 10, health: 5 }, healthRisk: 0,
          knowledgeBonus: ['fire'], statGain: { intelligence: 0.2, social: 0.2 },
          destreseDiscovery: ['cooking'], eventPool: [], zone: 'home',
          successTexts: ['El festí reuneix tota la tribu.', 'L\'aroma omple la cova. Tothom menja feliç.'],
          failTexts: ['El festí no surt com esperaves.', 'El menjar no és suficient per a tothom.'] },
        { id: 'preserve_food', name: 'Conservar Aliments', icon: '🏺', category: 'home',
          description: 'Tècniques per conservar menjar durant l\'hivern. Reserves assegurades.',
          requirements: {}, requiresSkill: 'cooking_mastery', statKey: 'intelligence',
          outputs: { food: 25, happiness: 5 }, healthRisk: 0, knowledgeBonus: ['fire'],
          statGain: { intelligence: 0.3 }, destreseDiscovery: ['cooking'], eventPool: [], zone: 'home',
          successTexts: ['Les reserves creixent. L\'hivern no us tocarà.', 'La tècnica de conservació és un èxit.'],
          failTexts: ['Els aliments es malbaraten.', 'La conservació no funciona avui.'] },
        // ── Fire Techniques ──
        { id: 'torch_hunt', name: 'Caça amb Torxes', icon: '🔦', category: 'survival',
          description: 'Caça nocturna amb torxes. Les preses no s\'esperen la llum.',
          requirements: {}, requiresSkill: 'fire_techniques', statKey: 'physical',
          outputs: { food: 28, happiness: 8 }, healthRisk: 6,
          riskReductions: { stone_tools: 0.3 }, knowledgeBonus: ['fire', 'stone_tools'],
          statGain: { physical: 0.4, intelligence: 0.2 }, destreseDiscovery: ['tracking'],
          eventPool: ['great_prey', 'dangerous_prey'], zone: 'forest',
          successTexts: ['Les torxes illuminen la presa.', 'La cacera nocturna és un èxit.'],
          failTexts: ['La foscor enganya.', 'La presa escapa a les ombres.'] },
        { id: 'signal_fires', name: 'Senyals de Foc', icon: '🚨', category: 'home',
          description: 'Usa el foc per comunicar-te amb tribus distants i cridar aliats.',
          requirements: {}, requiresSkill: 'fire_techniques', statKey: 'social',
          outputs: { familyReputation: 15, happiness: 10 }, healthRisk: 0, knowledgeBonus: ['fire'],
          statGain: { social: 0.4 }, destreseDiscovery: ['socialitzar'], eventPool: [], zone: 'wild',
          successTexts: ['El senyal és rebut! Aliats arriben.', 'El foc parla per tu.'],
          failTexts: ['El senyal no arriba prou lluny.', 'Ningú respon.'] },
        // ── Big Game Hunting ──
        { id: 'hunt_mammoth', name: 'Caçar el Mamut', icon: '🦣', category: 'survival',
          description: 'La gran caça. Perill extrem, recompensa llegendària.',
          requirements: { physical: 2 }, requiresSkill: 'big_game_hunting', statKey: 'physical',
          outputs: { food: 50, familyReputation: 15 }, healthRisk: 22,
          riskReductions: { stone_tools: 0.3 }, knowledgeBonus: ['stone_tools'],
          statGain: { physical: 0.6 }, destreseDiscovery: ['tracking'],
          eventPool: ['great_prey', 'dangerous_prey', 'injured_companion'], zone: 'forest',
          successTexts: ['El mamut cau! La tribu celebra durant dies.', 'Una llegenda neix avui.'],
          failTexts: ['El mamut és invencible.', 'La cacera del mamut acaba malament.'] },
        { id: 'hunt_bison', name: 'Caçar el Bisó', icon: '🦬', category: 'survival',
          description: 'El bisó és ràpid i perillós, però menys que el mamut.',
          requirements: {}, requiresSkill: 'big_game_hunting', statKey: 'physical',
          outputs: { food: 35, familyReputation: 8 }, healthRisk: 14,
          riskReductions: { stone_tools: 0.4 }, knowledgeBonus: ['stone_tools'],
          statGain: { physical: 0.5 }, destreseDiscovery: ['tracking'],
          eventPool: ['great_prey', 'injured_companion'], zone: 'forest',
          successTexts: ['El bisó cau. Menjar per setmanes.', 'La caça del bisó és un èxit.'],
          failTexts: ['El bisó s\'escapa.', 'La cacera fracassa avui.'] },
        // ── Advanced Crafting ──
        { id: 'craft_weapons', name: 'Forjar Armes', icon: '⚔️', category: 'knowledge',
          description: 'Armes especialitzades de pedra i os que milloren la caça del llinatge.',
          requirements: {}, requiresSkill: 'advanced_crafting', statKey: 'intelligence',
          outputs: { happiness: 12, familyReputation: 8 }, healthRisk: 0,
          knowledgeBonus: ['stone_tools'], statGain: { intelligence: 0.4, physical: 0.2 },
          destreseDiscovery: ['weaving'], eventPool: [], zone: 'town',
          successTexts: ['Armes millors per a tots els caçadors.', 'La pedra revela el seu potencial.'],
          failTexts: ['Les armes no queden com volies.', 'La pedra es trenca.'] },
        { id: 'craft_ornaments', name: 'Crear Ornaments', icon: '💎', category: 'knowledge',
          description: 'Joies i ornaments que incrementen el prestigi del llinatge.',
          requirements: {}, requiresSkill: 'advanced_crafting', statKey: 'intelligence',
          outputs: { familyReputation: 14, happiness: 15 }, healthRisk: 0, knowledgeBonus: [],
          statGain: { intelligence: 0.3, social: 0.2 },
          destreseDiscovery: ['weaving', 'art_narratiu'], eventPool: [], zone: 'town',
          successTexts: ['Els ornaments brillen. La tribu t\'admira.', 'L\'artesania parla per si sola.'],
          failTexts: ['L\'ornament no resulta com esperaves.', 'La feina queda sense acabar.'] },
        // ── Shamanism ──
        { id: 'healing_ritual', name: 'Ritual Curatiu', icon: '🌿', category: 'home',
          description: 'Ritual espiritual per guarir els membres malalts de la tribu.',
          requirements: {}, requiresSkill: 'shamanism', statKey: 'intelligence',
          outputs: { health: 25, happiness: 15 }, healthRisk: 0,
          knowledgeBonus: ['symbolic_thinking'], statGain: { intelligence: 0.3, social: 0.2 },
          destreseDiscovery: ['medicinal_plants'], eventPool: ['spiritual_vision'], zone: 'home',
          successTexts: ['La tribu es recupera.', 'El ritual funciona. La salut torna.'],
          failTexts: ['Els esperits no escolten avui.', 'El ritual no fa efecte.'] },
        { id: 'spirit_ceremony', name: 'Cerimònia Espiritual', icon: '🧿', category: 'home',
          description: 'Gran cerimònia que uneix la tribu al voltant de les forces del cosmos.',
          requirements: {}, requiresSkill: 'shamanism', statKey: 'social',
          outputs: { happiness: 30, familyReputation: 20 }, healthRisk: 0,
          knowledgeBonus: ['symbolic_thinking'], statGain: { social: 0.5, intelligence: 0.2 },
          destreseDiscovery: ['art_narratiu'], eventPool: ['spiritual_vision'], zone: 'town',
          successTexts: ['La cerimònia commou tothom.', 'Els esperits somriuen. La tribu s\'uneix.'],
          failTexts: ['La cerimònia no connecta.', 'El silenci dels esperits és decebedor.'] },
        // ── Cave Art ──
        { id: 'paint_cave', name: 'Pintura Rupestre', icon: '🎨', category: 'knowledge',
          description: 'Immortalitza les gestes del llinatge a les parets de les coves.',
          requirements: {}, requiresSkill: 'cave_art', statKey: 'intelligence',
          outputs: { happiness: 18, familyReputation: 8 }, healthRisk: 0,
          knowledgeBonus: ['symbolic_thinking'], statGain: { intelligence: 0.5 },
          destreseDiscovery: ['art_narratiu'], eventPool: ['spiritual_vision'], zone: 'wild',
          successTexts: ['Les figures prenen vida a la paret.', 'L\'art rupestre immortalitza el llinatge.'],
          failTexts: ['La inspiració no arriba avui.', 'Les figures queden sense ànima.'] },
        { id: 'carve_symbols', name: 'Gravar Símbols', icon: '🗿', category: 'knowledge',
          description: 'Grava símbols en pedra i os. Missatges per a les generacions futures.',
          requirements: {}, requiresSkill: 'cave_art', statKey: 'intelligence',
          outputs: { happiness: 12, familyReputation: 6 }, healthRisk: 0, knowledgeBonus: [],
          statGain: { intelligence: 0.4 }, destreseDiscovery: ['art_narratiu', 'weaving'],
          eventPool: [], zone: 'home',
          successTexts: ['Els símbols porten significat.', 'Cada incisió és un missatge al futur.'],
          failTexts: ['Els símbols resten buits.', 'La pedra resisteix avui.'] },
        // ── Proto Agriculture ──
        { id: 'plant_seeds', name: 'Plantar Llavors', icon: '🌱', category: 'survival',
          description: 'Primers intents de cultiu intencionat. Menjar estable i de baix risc.',
          requirements: {}, requiresSkill: 'proto_agriculture', statKey: 'intelligence',
          outputs: { food: 20, happiness: 10 }, healthRisk: 0, knowledgeBonus: ['sedentarism'],
          statGain: { intelligence: 0.4 }, destreseDiscovery: ['medicinal_plants'],
          eventPool: ['good_harvest', 'crop_failure'], zone: 'wild',
          successTexts: ['Les llavors germinen. L\'esperança floreix.', 'La terra respon al nostre treball.'],
          failTexts: ['Les llavors no arrelen.', 'La terra no és prou fèrtil aquí.'] },
        { id: 'tend_crops', name: 'Conrear', icon: '🌾', category: 'survival',
          description: 'Cuida els cultius i maximitza la collita de la temporada.',
          requirements: {}, requiresSkill: 'proto_agriculture', statKey: 'intelligence',
          outputs: { food: 30, happiness: 5 }, healthRisk: 0, knowledgeBonus: ['sedentarism'],
          statGain: { intelligence: 0.3 }, destreseDiscovery: [],
          eventPool: ['good_harvest', 'crop_failure'], zone: 'wild',
          successTexts: ['La collita creix ben cuidada.', 'El treball al camp dóna fruits.'],
          failTexts: ['La plaga ataca les plantes.', 'La sequera atura el creixement.'] },
        // ── Shelter Building ──
        { id: 'build_shelter', name: 'Construir Refugi', icon: '🏗️', category: 'home',
          description: 'Construeix estructures permanents per protegir la tribu del fred i la pluja.',
          requirements: {}, requiresSkill: 'shelter_building', statKey: 'physical',
          outputs: { health: 20, familyReputation: 15, happiness: 10 }, healthRisk: 0,
          knowledgeBonus: ['sedentarism'], statGain: { physical: 0.3, intelligence: 0.2 },
          destreseDiscovery: ['weaving'], eventPool: [], zone: 'home',
          successTexts: ['El refugi és sòlid i durador.', 'La tribu tindrà un lloc segur.'],
          failTexts: ['La construcció s\'esfondra.', 'El material no aguanta.'] },
        { id: 'fortify_camp', name: 'Fortificar el Camp', icon: '🛡️', category: 'home',
          description: 'Reforça les defenses del campament. La tribu dorm tranquil·la.',
          requirements: {}, requiresSkill: 'shelter_building', statKey: 'physical',
          outputs: { familyReputation: 18, happiness: 8 }, healthRisk: 0, knowledgeBonus: [],
          statGain: { physical: 0.4, intelligence: 0.1 }, destreseDiscovery: [], eventPool: [], zone: 'town',
          successTexts: ['El camp és ara un lloc defensable.', 'La tribu dorm tranquil·la.'],
          failTexts: ['Les defenses no aguanten.', 'El projecte és massa ambiciós per ara.'] },
      ],

      events: [
        { id: 'good_harvest', name: 'Collita Abundant', icon: '🍯',
          text: 'L\'anyada ha estat excepcional. Més del que podeu menjar.',
          options: [
            { id: 'store',     name: 'Emmagatzemar', fx: { always: { food: 20 } },                             desc: 'Reserves per al futur.' },
            { id: 'celebrate', name: 'Celebrar',      fx: { always: { happiness: 20, familyReputation: 5 } }, desc: 'La tribu et recordarà.' },
          ] },
        { id: 'rival_hunter', name: 'Caçador Rival', icon: '⚔️',
          text: 'Un altre caçador reclama el teu territori. La tensió és palesa.',
          options: [
            { id: 'confront', name: 'Confrontar', requiresStat: { physical: 3 }, successChance: 0.6,
              fx: { onSuccess: { familyReputation: 8, food: 12, happiness: 10 }, onFailure: { health: -15, familyReputation: -5 } },
              desc: 'Depèn de la força.' },
            { id: 'yield', name: 'Cedir', fx: { always: { food: -8, happiness: -10 } }, desc: 'Segur però humiliant.' },
          ] },
        { id: 'injured_companion', name: 'Company Ferit', icon: '🩹',
          text: 'Un company ha caigut durant la sortida. El pots abandonar o ajudar.',
          options: [
            { id: 'help',    name: 'Ajudar',    fx: { always: { health: -8, familyReputation: 12, happiness: 5 } }, desc: 'La tribu no oblida la generositat.' },
            { id: 'abandon', name: 'Continuar', fx: { always: { familyReputation: -10, happiness: -15 } },          desc: 'Sobreviuràs, però a un cost.' },
          ] },
        { id: 'harsh_winter', name: 'Hivern Dur', icon: '🌨️',
          text: 'El fred arriba abans d\'hora. Les reserves d\'aliments s\'esgoten.',
          options: [
            { id: 'conserve', name: 'Racionar',      fx: { always: { food: -20, happiness: -10, health: -5 } }, desc: 'Sobreviureu, just just.' },
            { id: 'trade',    name: 'Demanar ajuda', requiresStat: { social: 2 }, successChance: 0.7,
              fx: { onSuccess: { food: -10, happiness: 5, familyReputation: 3 }, onFailure: { food: -25, happiness: -15 } },
              desc: 'La tribu pot ajudar... o no.' },
          ] },
        { id: 'tribe_conflict', name: 'Conflicte Tribal', icon: '🔥',
          text: 'Hi ha tensió a la tribu. La teva posició és clau per resoldre-ho.',
          options: [
            { id: 'mediate', name: 'Mediar',  requiresStat: { social: 2 }, successChance: 0.65,
              fx: { onSuccess: { familyReputation: 10, happiness: 10 }, onFailure: { happiness: -10, health: -5 } },
              desc: 'Si tens la paraula, pots unir-los.' },
            { id: 'ignore',  name: 'Ignorar', fx: { always: { familyReputation: -8 } }, desc: 'No és el teu problema... ara.' },
          ] },
        { id: 'found_herb', name: 'Herba Medicinal', icon: '🌱',
          text: 'Trobes una planta desconeguda. Sembla útil però és arriscat provar-la.',
          options: [
            { id: 'try',  name: 'Provar',  successChance: 0.7, fx: { onSuccess: { health: 20, happiness: 10 }, onFailure: { health: -12 } }, desc: 'Pot curar o empitjorar.' },
            { id: 'pass', name: 'Ignorar', fx: { always: { food: 3 } }, desc: 'La deixes estar.' },
          ] },
        { id: 'found_shelter', name: 'Refugi Natural', icon: '🏔️',
          text: 'Descobreixes una cova perfecta. Podria ser la nova llar de la tribu.',
          options: [
            { id: 'claim',   name: 'Establir-se', fx: { always: { health: 10, familyReputation: 5, happiness: 10 } }, desc: 'Un bon refugi millora la vida.' },
            { id: 'pass_on', name: 'Continuar',   fx: { always: { food: 6 } },                                        desc: 'Continues buscant.' },
          ] },
        { id: 'great_prey', name: 'Gran Presa', icon: '🦬',
          text: 'Rastre d\'una presa excepcional. Però la persecució serà perillosa.',
          options: [
            { id: 'chase', name: 'Perseguir', requiresStat: { physical: 2 }, successChance: 0.55,
              fx: { onSuccess: { food: 35, familyReputation: 8, happiness: 15 }, onFailure: { health: -20, food: -5 } },
              desc: 'Recompensa enorme, risc real.' },
            { id: 'skip',  name: 'Deixar-la', fx: { always: { food: 10 } }, desc: 'Caça menor però segura.' },
          ] },
        { id: 'neighboring_tribe', name: 'Tribu Veïna', icon: '👥',
          text: 'Una tribu desconeguda s\'apropa al vostre territori. Les seves intencions no estan clares.',
          options: [
            { id: 'trade',  name: 'Negociar', requiresStat: { social: 2 }, successChance: 0.65,
              fx: { onSuccess: { food: 20, familyReputation: 12, happiness: 10 }, onFailure: { happiness: -8, familyReputation: -5 } },
              desc: 'Paraules obertes poden forjar una aliança.' },
            { id: 'defend', name: 'Defensar', requiresStat: { physical: 2 }, successChance: 0.6,
              fx: { onSuccess: { familyReputation: 10, happiness: 5 }, onFailure: { health: -15, food: -10 } },
              desc: 'Mostreu força. Que se\'n vagin.' },
          ] },
        { id: 'epidemic', name: 'Epidèmia', icon: '🤧',
          text: 'Una malaltia s\'escampa per la tribu. Alguns membres cauen malalts.',
          options: [
            { id: 'isolate', name: 'Aïllar malalts', fx: { always: { health: -15, familyReputation: -5, happiness: -10 } },
              desc: 'Contenciu la propagació al cost del benestar tribal.' },
            { id: 'treat',   name: 'Tractar-los', requiresStat: { intelligence: 2 }, successChance: 0.6,
              fx: { onSuccess: { health: -8, familyReputation: 10 }, onFailure: { health: -25, familyReputation: -8 } },
              desc: 'Useu el vostre coneixement per curar. Arriscat però noble.' },
          ] },
        { id: 'spiritual_vision', name: 'Visió Espiritual', icon: '✨',
          text: 'Durant el ritual, una de les vostres veus una visió. Un misteri del món us parla.',
          options: [
            { id: 'share',    name: 'Compartir la visió', fx: { always: { happiness: 18, familyReputation: 12 } },
              desc: 'La tribu s\'uneix al voltant del misteri.' },
            { id: 'meditate', name: 'Interioritzar',      fx: { always: { happiness: 10, health: 5 } },
              desc: 'Guardeu la visió per a vosaltres. La saviesa creix en silenci.' },
          ] },
        { id: 'rival_suitor', name: 'Pretendent Rival', icon: '💔',
          text: 'Un rival reclama la mateixa parella que tu. La tensió és palpable.',
          options: [
            { id: 'compete',  name: 'Competir',   requiresStat: { social: 2 }, successChance: 0.6,
              fx: { onSuccess: { happiness: 20, familyReputation: 10 }, onFailure: { happiness: -15, familyReputation: -8 } },
              desc: 'Demostreu el vostre valor. El cor tria.' },
            { id: 'withdraw', name: 'Retirar-se', fx: { always: { happiness: -12 } },
              desc: 'La prudència a vegades és sàvia.' },
          ] },
        { id: 'dangerous_prey', name: 'Presa Perillosa', icon: '🐯',
          text: 'La presa contraataca. De sobte, la caça es torna en vostra contra.',
          options: [
            { id: 'fight',   name: 'Resistir',   requiresStat: { physical: 3 }, successChance: 0.55,
              fx: { onSuccess: { food: 20, familyReputation: 8, happiness: 10 }, onFailure: { health: -25 } },
              desc: 'Feu front. O el domeu o us domina.' },
            { id: 'retreat', name: 'Retirar-se', fx: { always: { health: -8, happiness: -5 } },
              desc: 'Salveu la vida. La presa queda lliure.' },
          ] },
        { id: 'crop_failure', name: 'Plaga als Cultius', icon: '🪲',
          text: 'Una plaga ataca els vostres cultius incipients. Cal actuar ràpid.',
          options: [
            { id: 'fight_plague', name: 'Combatre la plaga', requiresStat: { intelligence: 2 }, successChance: 0.6,
              fx: { onSuccess: { food: -5, happiness: 5 }, onFailure: { food: -20, happiness: -10 } },
              desc: 'Useu el vostre coneixement agrícola.' },
            { id: 'abandon',      name: 'Abandonar el camp', fx: { always: { food: -15, happiness: -8 } },
              desc: 'Deixeu anar i busqueu menjar d\'altra manera.' },
          ] },
      ],

      destreses: [
        { id: 'medicinal_plants', name: 'Plantes Medicinals', icon: '🌿',
          description: 'Saps identificar les plantes que curen i les que maten.',
          effectDesc: '+5% Salut màxima al final de cada cicle.',
          effect: { healthRegenPct: 0.05 }, requires: { techIds: [] },
          transversal: false, discoveryChance: 0.25 },
        { id: 'fishing', name: 'Pesca', icon: '🎣',
          description: 'Saps trobar els millors llocs on pescar al riu.',
          effectDesc: '+50% Menjar extra quan recol·lectes.',
          effect: { gatherFoodPct: 0.5 }, requires: { techIds: [] },
          transversal: false, discoveryChance: 0.2 },
        { id: 'tracking', name: 'Rastreig', icon: '🐾',
          description: 'Llegeixes el terreny i el rastre de les preses millor que ningú.',
          effectDesc: '+20% als resultats de Caçar i Explorar.',
          effect: { huntMultBonus: 0.2 }, requires: { techIds: [] },
          transversal: false, discoveryChance: 0.25 },
        { id: 'weaving', name: 'Teixir', icon: '🧵',
          description: 'Teixeixes roba i abrics que protegeixen del fred i l\'esgotament.',
          effectDesc: 'La penalitat d\'envelliment és un 25% menor.',
          effect: { agingDamageReduction: 0.25 }, requires: { techIds: [] },
          transversal: true, discoveryChance: 0.2 },
        { id: 'cooking', name: 'Cuina Bàsica', icon: '🍳',
          description: 'Cuines els aliments sobre el foc. El valor nutritiu augmenta.',
          effectDesc: 'Consum de menjar al final de cicle -20%.',
          effect: { foodCostReduction: 0.2 }, requires: { techIds: ['fire'] },
          transversal: false, discoveryChance: 0.35 },
        { id: 'socialitzar', name: 'Socialitzar', icon: '💬',
          description: 'Saps crear llaços de confiança i fer que la tribu et segueixi.',
          effectDesc: '+20% als guanys de Reputació Familiar.',
          effect: { familyRepPct: 0.2 }, requires: { techIds: ['language_basics'] },
          transversal: false, discoveryChance: 0.25 },
        { id: 'art_narratiu', name: 'Art Narratiu', icon: '🎨',
          description: 'Expliques les gestes ancestrals al voltant del foc. La tribu recorda i s\'enforteix.',
          effectDesc: '+5 Felicitat al final de cada cicle.',
          effect: { happinessCycleBonus: 5 }, requires: { techIds: ['symbolic_thinking'] },
          transversal: true, discoveryChance: 0.2 },
      ],
    },

    // ══════════════════════════════════════════════════════════════════════
    //  ERA 2 — NEOLÍTIC  (skeleton — content to be designed)
    // ══════════════════════════════════════════════════════════════════════
    {
      id: 'neolitic',
      name: 'Neolític',
      icon: '🏺',
      lifeExpectancy: { base: 35, max: 55 },
      cyclesPerLife: { base: 12, max: 15 },
      agingCurve: { threshold: 8, baseLoss: 4, acceleration: 1.6 },
      maxChildren: 5,
      startingStats: { physical: 1, intelligence: 1, social: 1 },
      timeTotal: 6,
      foodPerTimePoint: 1.4,
      duration: 60,
      globalEvents: [],
      dynastySuffixes: ['de la Sembra', 'del Blat', 'de l\'Argila', 'del Riu', 'de la Pedra'],
      mechanics: {
        intensityOutputMults: [0.5, 1.1, 1.8],
        intensityRiskMults:   [0.4, 1.0, 2.2],
        intensityFailChances: [0.15, 0.3, 0.55],
        intensityTimeCosts:   [2, 4, 6],
        intensityLabels:      ['🌱 Suau', '⚡ Normal', '🔥 Intens'],
        statModBase:    0.65,
        statModPerStat: 0.12,
        statModMin:     0.5,
        statModMax:     1.8,
        knowledgeBonusPerTech: 0.15,
        maxLearnedSkills: 2,
        skillDiscoveryMinScore: 0.3,
        happinessDrift:   -2,
        happinessMin:     25,
        familyRepBonus:   2,
        childrenFoodCost: 2,
        famineModerate:        0.3,
        famineSevere:          0.6,
        famineChildDeathRisk:  0.7,
        famineHealthMult:      1.4,
        famineMaxLossModerate: 2,
        famineMaxLossSevere:   4,
        healthMaxFloor:        30,
        grownChildCycles:    3,
        grownChildBonus:     2,
        grownChildMaxCount:  2,
        largeChildThreshold: 3,
        largeChildBonus:     2,
        teachCostBase:      2,
        teachCostIncrement: 1,
        eventTriggerChance:  0.28,
        globalEventMinCycle: 4,
        globalEventChance:   0.1,
        partnerStatDivisor:       1.5,
        successionPhysicalFactor: 0.3,
        scorePerGeneration: 500,
        scorePerRep:        6,
        scorePerKnowledge:  120,
      },

      zones:    [],
      techs:    [],
      skills:   [],
      actions:  [],
      events:   [],
      destreses: [],
    },
  ],
};
