'use strict';

const GAME_DATA = {

  era: {
    id: 'prehistoria',
    name: 'Prehistòria',
    icon: '🦴',
    lifeExpectancy: { base: 30, max: 45 },
    cyclesPerLife: { base: 10, max: 14 },
    maxChildren: 6,
    startingStats: {
      health: 80, food: 40,
      physical: 1, intelligence: 1, social: 1,
      happiness: 60, familyReputation: 0,
    },
    timeTotal: 6,
    foodPerTimePoint: 1.7,
    duration: 60,
    toolTiers: [
      { level: 2, knowledgeId: 'stone_tools', earliest: 10, auto: 30, progressThreshold: 15 },
    ],
  },

  // statKey: which character stat affects this project's output
  projects: [
    {
      id: 'gather', name: 'Recol·lectar', icon: '🌿', category: 'survival',
      description: 'Baies, arrels i bolets. Segur però lent.',
      requirements: {},
      statKey: 'intelligence',
      outputs: { food: 15, happiness: 5, health: 2 },
      healthRisk: 0,
      knowledgeBonus: [], statGain: { intelligence: 0.3 },
      knowledgeDiscovery: ['cooking'],
      skillDiscovery: ['medicinal_plants', 'fishing'],
      eventPool: ['good_harvest', 'found_herb'],
      zone: 'wild',
      successTexts: ['Collita generosa!', 'El camp ens alimenta.', 'Prou per uns dies.'],
      failTexts: ['Poca cosa avui.', 'El bosc no dóna molt.'],
    },
    {
      id: 'hunt', name: 'Caçar', icon: '🦣', category: 'survival',
      description: 'Sortir a caçar. Risc alt, recompensa alta.',
      requirements: { physical: 2 },
      statKey: 'physical',
      outputs: { food: 22 },
      healthRisk: 10,
      riskReductions: { stone_tools: 0.5 },
      knowledgeBonus: ['stone_tools'], statGain: { physical: 0.4 },
      knowledgeDiscovery: [],
      skillDiscovery: ['tracking'],
      eventPool: ['rival_hunter', 'injured_companion', 'great_prey'],
      zone: 'forest',
      successTexts: ['Bona caça! La tribu celebra.', 'Gran presa avui!', 'El mamut cau.'],
      failTexts: ['Caça escassa.', 'Les preses ens escapen.', 'Tornem amb poc.'],
    },
    {
      id: 'craft_tools', name: 'Fabricar Eines', icon: '🪨', category: 'knowledge',
      description: 'Treballa la pedra i l\'os. Acumula progrés cap a eines millors.',
      requirements: { intelligence: 1 },
      statKey: 'intelligence',
      outputs: {},
      toolProgressGain: true,
      healthRisk: 0,
      knowledgeBonus: [], statGain: { intelligence: 0.5 },
      knowledgeDiscovery: ['fire'],
      skillDiscovery: ['weaving'],
      eventPool: [],
      zone: 'town',
      successTexts: ['Noves tècniques descobertes!', 'Les eines milloren.', 'La pedra revela els seus secrets.'],
      failTexts: ['Poc progrés avui.', 'Necessites més pràctica.'],
    },
    {
      id: 'observe_nature', name: 'Observar la Natura', icon: '🔍', category: 'knowledge',
      description: 'Contemplar l\'entorn. Acumula coneixement i pau interior.',
      requirements: {},
      statKey: 'intelligence',
      outputs: { happiness: 18 },
      healthRisk: 0,
      knowledgeBonus: [], statGain: { intelligence: 0.6 },
      knowledgeDiscovery: ['fire'],
      skillDiscovery: ['medicinal_plants', 'weaving'],
      eventPool: ['found_shelter'],
      zone: 'wild',
      successTexts: ['El món s\'obre als teus ulls.', 'Nova comprensió de la natura.', 'Descobreixes patrons ocults.'],
      failTexts: ['La ment vaga avui.', 'Reflexió sense conclusions.'],
    },
    {
      id: 'explore', name: 'Explorar', icon: '🗺️', category: 'survival',
      description: 'Aventurar-se lluny. Risc alt, recursos rars.',
      requirements: { physical: 3, knowledgeIds: ['stone_tools'] },
      statKey: 'physical',
      outputs: { food: 8 },
      healthRisk: 16,
      knowledgeBonus: ['stone_tools'], statGain: { physical: 0.5, intelligence: 0.2 },
      knowledgeDiscovery: [],
      skillDiscovery: ['tracking', 'fishing'],
      eventPool: ['found_shelter', 'injured_companion', 'great_prey'],
      zone: 'forest',
      successTexts: ['Terres noves! Recursos inesperats.', 'L\'horitzó et recompensa.', 'Una troballa excepcional.'],
      failTexts: ['El camí és dur i perillós.', 'Tornes cansat i buit.'],
    },
    {
      id: 'find_partner', name: 'Buscar Parella', icon: '💑', category: 'home',
      description: 'Socialitzar per trobar algú amb qui compartir el camí.',
      requirements: { social: 2 },
      requiresNoPartner: true,
      statKey: 'social',
      outputs: { happiness: 20, familyReputation: 5 },
      healthRisk: 0,
      knowledgeBonus: [], statGain: { social: 0.5 },
      knowledgeDiscovery: ['language_basics'],
      generatesPartner: true,
      eventPool: [],
      zone: 'town',
      successTexts: ['Has trobat algú especial.', 'La tribu celebra la unió.', 'Un nou capítol comença.'],
      failTexts: ['No és el moment.', 'El cor és pacient.'],
    },
    {
      id: 'have_children', name: 'Tenir Fills', icon: '👶', category: 'home',
      description: 'Créixer com a família. El futur del llinatge.',
      requirements: { health: 40, requiresPartner: true },
      statKey: 'social',
      outputs: { happiness: 15 },
      healthRisk: 0,
      knowledgeBonus: [], statGain: { social: 0.3 },
      generatesChild: true,
      eventPool: [],
      zone: 'home',
      successTexts: ['Benvingut/da al món!', 'El llinatge creix.', 'Un nou cor batega.'],
      failTexts: ['No és el moment per ampliar la família.'],
    },
    {
      id: 'care_home', name: 'Cuidar la Llar', icon: '🏠', category: 'home',
      description: 'Descansa i enforteix els llaços de la tribu. Recupera salut.',
      requirements: {},
      statKey: 'social',
      outputs: { health: 15, happiness: 12, familyReputation: 3 },
      healthRisk: 0,
      knowledgeBonus: [], statGain: { social: 0.3 },
      knowledgeDiscovery: ['language_basics', 'cooking'],
      skillDiscovery: ['weaving'],
      eventPool: ['tribe_conflict'],
      zone: 'home',
      successTexts: ['La tribu et recorda.', 'El descans et revitalitza.', 'La llar és font de força.'],
      failTexts: ['Difícil trobar calma avui.'],
    },
    {
      id: 'educate_child', name: 'Educar Fills', icon: '📖', category: 'home',
      description: 'Transmet una de les teves habilitats a un fill.',
      requirements: { requiresChild: true, requiresLearnedSkill: true },
      statKey: 'social',
      outputs: { happiness: 8, familyReputation: 3 },
      healthRisk: 0,
      knowledgeBonus: [], statGain: { social: 0.2, intelligence: 0.1 },
      knowledgeDiscovery: [], skillDiscovery: [],
      teachesSkill: true,
      eventPool: [],
      zone: 'home',
      successTexts: ['El fill aprèn ràpidament.', 'Un moment inoblidable.', 'Sents com el llinatge creix en saviesa.'],
      failTexts: [],
    },
  ],

  events: [
    {
      id: 'good_harvest', name: 'Collita Abundant', icon: '🍯',
      text: 'L\'anyada ha estat excepcional. Més del que podeu menjar.',
      options: [
        { id: 'store',     name: 'Emmagatzemar', fx: { always: { food: 20 } },                             desc: 'Reserves per al futur.' },
        { id: 'celebrate', name: 'Celebrar',      fx: { always: { happiness: 20, familyReputation: 5 } }, desc: 'La tribu et recordarà.' },
      ],
    },
    {
      id: 'rival_hunter', name: 'Caçador Rival', icon: '⚔️',
      text: 'Un altre caçador reclama el teu territori. La tensió és palesa.',
      options: [
        { id: 'confront', name: 'Confrontar', requiresStat: { physical: 3 }, successChance: 0.6,
          fx: { onSuccess: { familyReputation: 8, food: 12, happiness: 10 }, onFailure: { health: -15, familyReputation: -5 } },
          desc: 'Depèn de la força.' },
        { id: 'yield', name: 'Cedir', fx: { always: { food: -8, happiness: -10 } }, desc: 'Segur però humiliant.' },
      ],
    },
    {
      id: 'injured_companion', name: 'Company Ferit', icon: '🩹',
      text: 'Un company ha caigut durant la sortida. El pots abandonar o ajudar.',
      options: [
        { id: 'help',    name: 'Ajudar',    fx: { always: { health: -8, familyReputation: 12, happiness: 5 } }, desc: 'La tribu no oblida la generositat.' },
        { id: 'abandon', name: 'Continuar', fx: { always: { familyReputation: -10, happiness: -15 } },          desc: 'Sobreviuràs, però a un cost.' },
      ],
    },
    {
      id: 'harsh_winter', name: 'Hivern Dur', icon: '🌨️',
      text: 'El fred arriba abans d\'hora. Les reserves d\'aliments s\'esgoten.',
      options: [
        { id: 'conserve', name: 'Racionar',      fx: { always: { food: -20, happiness: -10, health: -5 } }, desc: 'Sobreviureu, just just.' },
        { id: 'trade',    name: 'Demanar ajuda', requiresStat: { social: 2 }, successChance: 0.7,
          fx: { onSuccess: { food: -10, happiness: 5, familyReputation: 3 }, onFailure: { food: -25, happiness: -15 } },
          desc: 'La tribu pot ajudar... o no.' },
      ],
    },
    {
      id: 'tribe_conflict', name: 'Conflicte Tribal', icon: '🔥',
      text: 'Hi ha tensió a la tribu. La teva posició és clau per resoldre-ho.',
      options: [
        { id: 'mediate', name: 'Mediar',  requiresStat: { social: 2 }, successChance: 0.65,
          fx: { onSuccess: { familyReputation: 10, happiness: 10 }, onFailure: { happiness: -10, health: -5 } },
          desc: 'Si tens la paraula, pots unir-los.' },
        { id: 'ignore',  name: 'Ignorar', fx: { always: { familyReputation: -8 } }, desc: 'No és el teu problema... ara.' },
      ],
    },
    {
      id: 'found_herb', name: 'Herba Medicinal', icon: '🌱',
      text: 'Trobes una planta desconeguda. Sembla útil però és arriscat provar-la.',
      options: [
        { id: 'try',  name: 'Provar',  successChance: 0.7, fx: { onSuccess: { health: 20, happiness: 10 }, onFailure: { health: -12 } }, desc: 'Pot curar o empitjorar.' },
        { id: 'pass', name: 'Ignorar', fx: { always: { food: 3 } },  desc: 'La deixes estar.' },
      ],
    },
    {
      id: 'found_shelter', name: 'Refugi Natural', icon: '🏔️',
      text: 'Descobreixes una cova perfecta. Podria ser la nova llar de la tribu.',
      options: [
        { id: 'claim',   name: 'Establir-se', fx: { always: { health: 10, familyReputation: 5, happiness: 10 } }, desc: 'Un bon refugi millora la vida.' },
        { id: 'pass_on', name: 'Continuar',   fx: { always: { food: 6 } },                                        desc: 'Continues buscant.' },
      ],
    },
    {
      id: 'great_prey', name: 'Gran Presa', icon: '🦬',
      text: 'Rastre d\'una presa excepcional. Però la persecució serà perillosa.',
      options: [
        { id: 'chase', name: 'Perseguir', requiresStat: { physical: 2 }, successChance: 0.55,
          fx: { onSuccess: { food: 35, familyReputation: 8, happiness: 15 }, onFailure: { health: -20, food: -5 } },
          desc: 'Recompensa enorme, risc real.' },
        { id: 'skip',  name: 'Deixar-la', fx: { always: { food: 10 } }, desc: 'Caça menor però segura.' },
      ],
    },
  ],

  knowledge: [
    {
      id: 'fire', name: 'Foc', icon: '🔥',
      description: 'Dominar el foc canvia les possibilitats de la tribu.',
      statBonus: { health: 5 }, inheritanceRate: 1.0, discoveryChance: 0.3,
      unlocksProjectIds: [],
    },
    {
      id: 'stone_tools', name: 'Eines de Pedra', icon: '🪨',
      description: 'Eines millorades per a la caça i l\'exploració.',
      statBonus: {}, inheritanceRate: 1.0, discoveryChance: 0.45,
      unlocksProjectIds: ['explore'],
    },
    {
      id: 'language_basics', name: 'Llengua Bàsica', icon: '🗣️',
      description: 'Comunicar-se millor enforteix els llaços tribals.',
      statBonus: { social: 1 }, inheritanceRate: 1.0, discoveryChance: 0.3,
      unlocksProjectIds: [],
    },
    {
      id: 'cooking', name: 'Cocció', icon: '🍳',
      description: 'Cuinar els aliments sobre el foc en augmenta el valor nutritiu.',
      effectDesc: 'Consum de menjar al final de cicle -20%.',
      statBonus: {}, inheritanceRate: 1.0, discoveryChance: 0.3,
      requires: { knowledgeIds: ['fire'] },
      unlocksProjectIds: [],
    },
  ],

  learnedSkills: [
    { id: 'medicinal_plants', name: 'Plantes Medicinals', icon: '🌿',
      description: 'Saps identificar les plantes que curen i les que maten.',
      effectDesc: '+5 Salut al final de cada cicle.',
      effect: { healthRegen: 5 },
      discoveryChance: 0.25 },
    { id: 'fishing', name: 'Pesca', icon: '🎣',
      description: 'Saps trobar els millors llocs on pescar al riu.',
      effectDesc: '+8 Menjar addicional cada vegada que recol·lectes.',
      effect: { gatherFoodBonus: 8 },
      discoveryChance: 0.2 },
    { id: 'tracking', name: 'Rastreig', icon: '🐾',
      description: 'Llegeixes el terreny i el rastre de les preses millor que ningú.',
      effectDesc: '+20% als resultats de Caçar i Explorar.',
      effect: { huntMultBonus: 0.2 },
      discoveryChance: 0.25 },
    { id: 'weaving', name: 'Teixir', icon: '🧵',
      description: 'Teixeixes roba i abrics que protegeixen del fred i l\'esgotament.',
      effectDesc: 'La penalitat d\'envelliment és un 25% menor.',
      effect: { agingDamageReduction: 0.25 },
      discoveryChance: 0.2 },
  ],

  traits: [
    { id: 'great_strength',     name: 'Força excepcional',  icon: '⚡', statKey: 'physical',
      desc: 'Salut màxima incrementada en 15.',
      effect: { maxHealth: 15 }, inheritChance: 0.4 },
    { id: 'natural_resilience', name: 'Resistència natural', icon: '🛡️', statKey: 'physical',
      desc: 'L\'envelliment li afecta la meitat.',
      effect: { agingResist: true }, inheritChance: 0.5 },
    { id: 'sharp_intuition',    name: 'Intuïció afilada',   icon: '🔮', statKey: 'intelligence',
      desc: 'Descobreix coneixements amb +20% de probabilitat.',
      effect: { discoveryBonus: 0.2 }, inheritChance: 0.3 },
    { id: 'quick_learner',      name: 'Aprenent ràpid',     icon: '📖', statKey: 'intelligence',
      desc: 'Guanya habilitats un 25% més ràpidament.',
      effect: { statGainBonus: 0.25 }, inheritChance: 0.3 },
    { id: 'born_leader',        name: 'Líder nat',           icon: '👑', statKey: 'social',
      desc: 'Comença amb +10 reputació familiar.',
      effect: { stat: 'familyReputation', value: 10 }, inheritChance: 0.35 },
    { id: 'gift_of_speech',     name: 'Do de la paraula',   icon: '🗣️', statKey: 'social',
      desc: 'Carisma innat: +1 Social.',
      effect: { stat: 'social', value: 1 }, inheritChance: 0.4 },
    { id: 'adaptable',          name: 'Adaptable',           icon: '🌿', statKey: 'balanced',
      desc: 'S\'adapta a qualsevol situació: +15 Felicitat inicial.',
      effect: { stat: 'happiness', value: 15 }, inheritChance: 0.25 },
  ],

  namesMasc: ['Brac', 'Arn', 'Dal', 'Kur', 'Mog', 'Thag', 'Bok', 'Drak', 'Fal', 'Gar', 'Huk', 'Jok'],
  namesFem:  ['Mira', 'Sela', 'Una', 'Bera', 'Kala', 'Thea', 'Nara', 'Lira', 'Vela', 'Hara', 'Yuna', 'Asha'],

  virtueLabels: {
    physical:     ['La seva força és llegendària des de petit', 'El cos mai li falla quan importa', 'Nascut/da per a la cacera'],
    intelligence: ['Té un talent innat per entendre el món', 'La curiositat el/la guia on altres no s\'atreveixen', 'La ment sempre un pas endavant'],
    social:       ['Fa amics allà on va', 'La tribu el/la segueix sense dubtar', 'Té el do de la paraula'],
    balanced:     ['No destaca en res però mai falla en res', 'Un equilibri que pocs assoleixen', 'La fiabilitat és la seva virtut'],
  },

  milestones: [
    { id: 'first_fire',      name: 'Mestre del Foc',        icon: '🔥', desc: 'Descobrir el foc',               points: 300 },
    { id: 'great_hunter',    name: 'Gran Caçador/a',         icon: '🦣', desc: '5 caceres exitoses',             points: 250 },
    { id: 'long_lived',      name: 'Longeu/a',               icon: '⏳', desc: 'Sobreviure fins als 40+ anys',   points: 200 },
    { id: 'dynasty_founded', name: 'Fundador/a de Dinastia', icon: '🏛️', desc: 'Iniciar la 2a generació',        points: 400 },
    { id: 'all_knowledge',   name: 'Buscador/a de Saviesa',  icon: '📜', desc: 'Descobrir tots els coneixements', points: 350 },
    { id: 'tribe_respected', name: 'Respectat/da per la Tribu', icon: '👑', desc: 'Reputació > 50',             points: 300 },
    { id: 'family_complete', name: 'Família Completa',       icon: '👨‍👩‍👧', desc: 'Tenir parella i 2+ fills',       points: 300 },
  ],
};
